<style>
    .block{

        padding:5px 10px;
        font-size: 14px;
        line-height: 2;
    }

    .accessibility-content {
        width: 75%;
    }
    .step{
        width:72%;
        float: left;
    }

    .step-heading {
        font-size: 16px;
    }

    .about{
        width:18%;
        float: left;
        margin-left:18px;
    }
    ul{
        list-style-type: none;
    }
    span{
        font-weight: 600;
    }
    .accessibility .action-advanced-reports {
        float: right;
    }

</style>
<div class="accessibility">
    <h1>Accessibility Enabler</h1>
    <a href="https://a11yenabler.hikeorders.com/user/login?utm_source=magento-plugin&utm_medium=open-dashboard&utm_campaign=magento-app-setup " target="_blank" class="action-advanced-reports">
        Open Dashboard
    </a>
</div>
<div class="block accessibility-content">
    This plugin increases accessibility compliance with WCAG 2.0 ,ATAG 2.0,ADA & Section 508 without changing your website's existing code. This is a complete accessibility plugin available for Magento2
</div>
<br>
