<br/>
<br/>
<div class="step block">
    <span class="step-heading">Step by step guide to get this extension working</span>
    <ul>
        <li>
            1. Create an accessibility enabler account : <a target="_blank" href="https://a11yenabler.hikeorders.com/user/register?utm_source=magento-plugin&utm_medium=create-account&utm_campaign=magento-app-setup">Get Started</a>
        </li>
        <li>
            2. Go through the on-boarding process. Its just 4 step process
        </li>
        <li>
            3. The on-boarding process gives you an OrgID. Copy-Paste in above text box and save it.
        </li>
        <li>
            4. Go back to on-boarding process and verify your installation.
        </li>
        <li>
            5. That's its done. Go to your site front-end and you will see accessibility enabler toolbar.
        </li>
    </ul>
</div>
<div class="about block">
    <span class="step-heading">About this extension</span>
    <ul>
        <li>
            <a target="_blank" href="https://hikeorders.com/accessibility/pricing/?utm_source=magento-plugin&utm_medium=about-plugin&utm_campaign=magento-app-setup">Pricing & Free trial</a>
        </li>
        <li>
            <a target="_blank" target="_blank" href="https://hikeorders.com/accessibility/main-accessibility-features/?utm_source=magento-plugin&utm_medium=about-plugin&utm_campaign=magento-app-setup">Feature</a>
        </li>
        <li>
            <a target="_blank" href="https://hikeorders.com/support/accessibility-enabler-support-center/?utm_source=magento-plugin&utm_medium=about-plugin&utm_campaign=magento-app-setup">Help / FAQ</a>
        </li>
        <li>
            <a target="_blank" href="https://hikeorders.com/accessibility/home/?utm_source=magento-plugin&utm_medium=about-plugin&utm_campaign=magento-app-setup">About</a>
        </li>
    </ul>
</div>
